language: cpp

compiler:
  - clang++

install:
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-std=c++17"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - cmake .
  - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}"
  - ls
  - ./base
